--------------------------------------------------------
--  파일이 생성됨 - 목요일-4월-09-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table TBL_COMMENT
--------------------------------------------------------

  CREATE TABLE "ADMIN"."TBL_COMMENT" 
   (	"U_ID" VARCHAR2(50 BYTE), 
	"C_NUMBER" NUMBER(4,0), 
	"C_F_ID" VARCHAR2(20 BYTE), 
	"C_TEXT" VARCHAR2(1000 BYTE), 
	"C_DATE" VARCHAR2(11 BYTE), 
	"U_NICKNAME" VARCHAR2(8 BYTE), 
	"C_P_NUMBER" NUMBER(4,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into ADMIN.TBL_COMMENT
SET DEFINE OFF;
Insert into ADMIN.TBL_COMMENT (U_ID,C_NUMBER,C_F_ID,C_TEXT,C_DATE,U_NICKNAME,C_P_NUMBER) values ('CITONONGRUR65CA3AAIYAIQNGE',436,'1000000110','<p style="font-size: small;color: gray;">削除されたコメントです','2020-04-09','yahoolog',null);
Insert into ADMIN.TBL_COMMENT (U_ID,C_NUMBER,C_F_ID,C_TEXT,C_DATE,U_NICKNAME,C_P_NUMBER) values ('CITONONGRUR65CA3AAIYAIQNGE',437,'1000000110','<p style="font-size: small;color: gray;">削除されたコメントです','2020-04-09','yahoolog',436);
--------------------------------------------------------
--  DDL for Index SYS_C007036
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMIN"."SYS_C007036" ON "ADMIN"."TBL_COMMENT" ("C_NUMBER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table TBL_COMMENT
--------------------------------------------------------

  ALTER TABLE "ADMIN"."TBL_COMMENT" ADD PRIMARY KEY ("C_NUMBER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ADMIN"."TBL_COMMENT" MODIFY ("C_F_ID" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."TBL_COMMENT" MODIFY ("C_NUMBER" NOT NULL ENABLE);
